/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author Usuario
 */
public class FrmArriendos extends javax.swing.JInternalFrame {

    ArriendoDAO aDAO = new ArriendoDAO();
    ClienteDAO cDAO = new ClienteDAO();
    LibroDAO lDAO = new LibroDAO();
    private String accion;

    /**
     * Creates new form FrmArriendos
     */
    public FrmArriendos() {
        initComponents();
        this.listar();
        this.cargarClientes();
        this.cargarLibros();
        this.accion = "guardar";
        txtId.setVisible(false);
        lblTipoPago.setVisible(false);
        cboTipoPago.setVisible(false);
    }

    private void listar() {
        ArrayList<Object> lista = aDAO.getListArriendosPend();
        DefaultTableModel modeloTabla;

        String[] titulos = {"ID Boleta", "Trabajador", "Cliente", "Precio neto", "Precio IVA", "Fecha arriendo", "Fecha estimada de devolucion", "Libro"};
        modeloTabla = new DefaultTableModel(null, titulos);

        for (Object obj : lista) {
            Arriendo arriendo = (Arriendo) obj;
            Object[] row = new Object[8];
            row[0] = arriendo.getFactura().getIdFactura();
            row[1] = arriendo.getTrabajador().getNombre();
            row[2] = arriendo.getCliente().getNombre();
            row[3] = "$" + arriendo.getFactura().getPrecioNeto();
            row[4] = "$" + arriendo.getFactura().getPrecioIva();
            row[5] = arriendo.getFactura().getFechaCompra();
            row[6] = arriendo.getFactura().getFechaEstimada();
            row[7] = arriendo.getLibro().getTitulo();
            modeloTabla.addRow(row);
        }
        tablaListadoPendientes.setModel(modeloTabla);
        tabGeneral.setEnabledAt(1, false);
    }

    private void limpiar() {
        txtFecha.setText("");
        this.accion = "guardar";
    }

    private void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "System", JOptionPane.ERROR_MESSAGE);
    }

    private void mensajeOk(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "System", JOptionPane.INFORMATION_MESSAGE);
    }

    private void cargarClientes() {
        DefaultComboBoxModel items = new DefaultComboBoxModel();
        ArrayList<Object> lista = cDAO.getList();

        for (Object obj : lista) {
            Cliente cl = (Cliente) obj;
            items.addElement(cl);
        }
        cboClientes.setModel(items);
    }

    private void cargarLibros() {
        DefaultComboBoxModel items = new DefaultComboBoxModel();
        ArrayList<Object> lista = lDAO.getList();

        for (Object obj : lista) {
            Libro libro = (Libro) obj;
            if (libro.getEstado() == 3) {
                items.addElement(libro);
            }

        }
        cboLibros.setModel(items);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGeneral = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoPendientes = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblClientes = new javax.swing.JLabel();
        cboClientes = new javax.swing.JComboBox<>();
        lblLibro = new javax.swing.JLabel();
        cboLibros = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblTipoPago = new javax.swing.JLabel();
        cboTipoPago = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Arriendos");

        tabGeneral.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaListadoPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaListadoPendientes);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(btnNuevo)
                .addGap(166, 166, 166)
                .addComponent(btnPagar)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnPagar))
                .addGap(0, 104, Short.MAX_VALUE))
        );

        tabGeneral.addTab("Listado ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblFecha.setText("Fecha estimada devolución(*)");

        lblClientes.setText("Clientes(*)");

        lblLibro.setText("Libro(*)");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblTipoPago.setText("Tipo de pago(*)");

        cboTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Debito", "Credito" }));

        jLabel1.setText("(*) Indica campo obligatorio");

        jLabel2.setText("YYYY/MM/DD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVolver))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblFecha)
                                            .addGap(45, 45, 45)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblTipoPago)
                                            .addGap(54, 54, 54)
                                            .addComponent(cboTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(95, 95, 95)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClientes)
                                    .addComponent(lblLibro))))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboLibros, 0, 150, Short.MAX_VALUE)
                            .addComponent(cboClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel2)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClientes)
                    .addComponent(cboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLibro)
                    .addComponent(lblTipoPago)
                    .addComponent(cboTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolver))
                .addGap(121, 121, 121))
        );

        tabGeneral.addTab("Mantenimiento", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        tabGeneral.setEnabledAt(0, true);
        tabGeneral.setEnabledAt(1, false);
        tabGeneral.setSelectedIndex(0);
        lblTipoPago.setVisible(false);
        cboTipoPago.setVisible(false);
        lblLibro.setVisible(true);
        lblClientes.setVisible(true);
        cboClientes.setVisible(true);
        cboLibros.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtFecha.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese una fecha válida", "System", JOptionPane.WARNING_MESSAGE);
            txtFecha.requestFocus();
            return;
        }

        if (this.accion.equals("guardar")) {
            Cliente cliente = (Cliente) cboClientes.getSelectedItem();
            Libro libro = (Libro) cboLibros.getSelectedItem();
            String fechaEstimada = txtFecha.getText();
            Factura factura = new Factura(libro.getPrecio(), fechaEstimada);
            Arriendo arriendo = new Arriendo(FrmLogin.user.getTrabajador(), cliente, factura, libro);
            if (aDAO.insertar(arriendo)) {
                this.mensajeOk("Arriendo registrado existosamente");
                this.limpiar();
                this.listar();
                tabGeneral.setEnabledAt(0, true);
                tabGeneral.setEnabledAt(1, false);
                tabGeneral.setSelectedIndex(0);
            } else {
                this.mensajeError("Ocurrio un error al intentar registrar el arriendo");
            }
        } else {
            int id = Integer.parseInt(txtId.getText());
            String fecha = txtFecha.getText();
            Arriendo arriendo = (Arriendo) aDAO.buscar(id);
            int idPago = cboTipoPago.getSelectedIndex();
            int idCbo;
            switch (idPago) {
                case 0 ->
                    idCbo = 1;
                case 1 ->
                    idCbo = 2;
                case 2 ->
                    idCbo = 3;
                default ->
                    throw new AssertionError();
            }
            arriendo.getFactura().setIdPago(idCbo);
            Arriendo ar = new Arriendo(arriendo.getIdArriendo(), arriendo.getTrabajador(), arriendo.getCliente(), arriendo.getFactura(), arriendo.getLibro(), fecha);
            if (aDAO.insertarArriendo(ar)) {
                int diasPasados = aDAO.buscarMulta(id);
                int multa = 1500;
                if (diasPasados > 0) {
                    if (aDAO.insertarMulta(id, ((diasPasados * multa) + ar.getLibro().getPrecio()))) {
                        this.mensajeOk("Tienes una multa de " + ((diasPasados * multa) + ar.getLibro().getPrecio()) + " por pagar");
                        this.limpiar();
                        this.listar();
                        tabGeneral.setEnabledAt(0, true);
                        tabGeneral.setEnabledAt(1, false);
                        tabGeneral.setSelectedIndex(0);
                    }
                } else {
                    this.mensajeOk("Arriendo pagado existosamente");
                    this.limpiar();
                    this.listar();
                    tabGeneral.setEnabledAt(0, true);
                    tabGeneral.setEnabledAt(1, false);
                    tabGeneral.setSelectedIndex(0);
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        if (tablaListadoPendientes.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoPendientes.getValueAt(tablaListadoPendientes.getSelectedRow(), 0));

            txtId.setText(id);

            tabGeneral.setEnabledAt(0, false);
            tabGeneral.setEnabledAt(1, true);
            tabGeneral.setSelectedIndex(1);
            lblTipoPago.setVisible(true);
            cboTipoPago.setVisible(true);
            lblLibro.setVisible(false);
            lblClientes.setVisible(false);
            cboClientes.setVisible(false);
            cboLibros.setVisible(false);
            lblFecha.setText("Fecha entrega");
            this.accion = "pagar";
            btnGuardar.setText("Pagar");

        } else {
            this.mensajeError("Seleccione 1 registro a editar.");
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        tabGeneral.setEnabledAt(1, true);
        tabGeneral.setEnabledAt(0, false);
        tabGeneral.setSelectedIndex(1);
        this.accion = "guardar";
        btnGuardar.setText("Guardar");
        lblLibro.setVisible(true);
        lblClientes.setVisible(true);
        cboClientes.setVisible(true);
        cboLibros.setVisible(true);
        lblFecha.setText("Fecha estimada de devolución");
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboClientes;
    private javax.swing.JComboBox<String> cboLibros;
    private javax.swing.JComboBox<String> cboTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblTipoPago;
    private javax.swing.JTabbedPane tabGeneral;
    private javax.swing.JTable tablaListadoPendientes;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
