/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.ClienteDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author Usuario
 */
public class FrmClientes extends javax.swing.JInternalFrame {

    ClienteDAO cDAO = new ClienteDAO();
    String accion;

    /**
     * Creates new form FrmClientes
     */
    public FrmClientes() {
        initComponents();
        this.listar();
        this.accion = "guardar";
        txtId.setVisible(false);
        txtCorreo.setVisible(false);
        txtDireccion.setVisible(false);
        txtTelefono.setVisible(false);
        lblCorreo.setVisible(false);
        lblTelefono.setVisible(false);
        lblDireccion.setVisible(false);
    }

    private void listar() {
        ArrayList<Object> lista = cDAO.getList();
        DefaultTableModel modeloTabla;

        String[] titulos = {"ID", "RUT", "Nombre", "Apellido", "Fecha de nacimineto", "Estado"};
        modeloTabla = new DefaultTableModel(null, titulos);

        for (Object obj : lista) {
            Cliente cliente = (Cliente) obj;
            Object[] row = new Object[6];
            row[0] = cliente.getIdCliente();
            row[1] = cliente.getRut();
            row[2] = cliente.getNombre();
            row[3] = cliente.getApellido();
            row[4] = cliente.getFechaNacimiento();
            switch (cliente.getEstado()) {
                case 1:
                    row[5] = "Activo";
                    break;
                case 2:
                    row[5] = "Inactivo";
                    break;
                default:
                    throw new AssertionError();
            }
            modeloTabla.addRow(row);
        }
        tablaListadoClientes.setModel(modeloTabla);
        tabGeneral.setEnabledAt(1, false);
    }

    private void limpiar() {
        txtApellido.setText("");
        txtId.setText("");
        txtNombre.setText("");
        txtRut.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtFecha.setText("");
        this.accion = "guardar";
    }

    private void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "System", JOptionPane.ERROR_MESSAGE);
    }

    private void mensajeOk(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "System", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGeneral = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoClientes = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Clientes");

        tabGeneral.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaListadoClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaListadoClientes);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnActivar.setText("Activar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        btnDesactivar.setText("Desactivar");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnNuevo)
                .addGap(93, 93, 93)
                .addComponent(btnActivar)
                .addGap(81, 81, 81)
                .addComponent(btnDesactivar)
                .addGap(95, 95, 95)
                .addComponent(btnEditar)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnActivar)
                    .addComponent(btnDesactivar)
                    .addComponent(btnEditar))
                .addGap(0, 103, Short.MAX_VALUE))
        );

        tabGeneral.addTab("Listado", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("RUT(*)");

        jLabel2.setText("Nombre(*)");

        jLabel3.setText("Apellido(*)");

        jLabel4.setText("Fecha de nacimiento");

        jLabel5.setText("YYYY/MM/DD");

        lblDireccion.setText("Direccion(*)");

        lblTelefono.setText("Telefono(*)");

        lblCorreo.setText("Correo(*)");

        jLabel9.setText("(*) Indica campo obligatorio.");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel5)
                        .addGap(188, 188, 188)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRut)
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDireccion)
                                    .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnGuardar)
                        .addGap(126, 126, 126)
                        .addComponent(btnVolver)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolver))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        tabGeneral.addTab("Mantenimiento", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabGeneral)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabGeneral)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        tabGeneral.setEnabledAt(1, true);
        tabGeneral.setEnabledAt(0, false);
        tabGeneral.setSelectedIndex(1);
        this.accion = "guardar";
        btnGuardar.setText("Guardar");
        txtCorreo.setVisible(true);
        txtDireccion.setVisible(true);
        txtTelefono.setVisible(true);
        lblCorreo.setVisible(true);
        lblTelefono.setVisible(true);
        lblDireccion.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        if (tablaListadoClientes.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 0));
            String nombre = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 2));
            String estado = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 5));
            if (!estado.equals("Activo")) {
                if (JOptionPane.showConfirmDialog(this, "Deseas activar al cliente: " + nombre + " ?", "Activar", JOptionPane.YES_NO_OPTION) == 0) {

                    if (cDAO.activar(Integer.parseInt(id))) {
                        this.mensajeOk("Registro activado");
                        this.listar();
                    } else {
                        this.mensajeError("Error, el regristro no pudo ser activado");
                    }
                }
            } else {
                this.mensajeError("El cliente ya está ACTIVO");
            }
        } else {
            this.mensajeError("Seleccione 1 registro a activar.");
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        if (tablaListadoClientes.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 0));
            String nombre = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 2));
            String estado = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 5));
            if (!estado.equals("Inactivo")) {
                if (JOptionPane.showConfirmDialog(this, "Deseas desactivar el cliente: " + nombre + " ?", "Desactivar", JOptionPane.YES_NO_OPTION) == 0) {

                    if (cDAO.eliminar(Integer.parseInt(id))) {
                        this.mensajeOk("Registro desactivado");
                        this.listar();
                    } else {
                        this.mensajeError("Error, el regristro no pudo ser desactivado");
                    }
                }
            } else {
                this.mensajeError("El cliente ya está DESACTIVADO");
            }
        } else {
            this.mensajeError("Seleccione 1 registro a activar.");
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tablaListadoClientes.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 0));
            String rut = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 1));
            String nombre = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 2));
            String apellido = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 3));
            String fecha = String.valueOf(tablaListadoClientes.getValueAt(tablaListadoClientes.getSelectedRow(), 4));

            txtId.setText(id);
            txtNombre.setText(nombre);
            txtRut.setText(rut);
            txtApellido.setText(apellido);
            txtFecha.setText(fecha);

            tabGeneral.setEnabledAt(0, false);
            tabGeneral.setEnabledAt(1, true);
            tabGeneral.setSelectedIndex(1);
            this.accion = "editar";
            btnGuardar.setText("Editar");

        } else {
            this.mensajeError("Seleccione 1 registro a editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        tabGeneral.setEnabledAt(0, true);
        tabGeneral.setEnabledAt(1, false);
        tabGeneral.setSelectedIndex(0);
        txtCorreo.setVisible(false);
        txtDireccion.setVisible(false);
        txtTelefono.setVisible(false);
        lblCorreo.setVisible(false);
        lblTelefono.setVisible(false);
        lblDireccion.setVisible(false);
        this.limpiar();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Cliente cl;
        if (txtNombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre válido", "System", JOptionPane.WARNING_MESSAGE);
            txtNombre.requestFocus();
            return;
        }
        if (txtApellido.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un apellido válido", "System", JOptionPane.WARNING_MESSAGE);
            txtApellido.requestFocus();
            return;
        }
        if (txtRut.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un rut válido", "System", JOptionPane.WARNING_MESSAGE);
            txtRut.requestFocus();
            return;
        }
     
        if (this.accion.equals("editar")) {
            int id = Integer.parseInt(txtId.getText());
            String rut = txtRut.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String fecha = txtFecha.getText();

            cl = new Cliente(id, rut, nombre, apellido, fecha);

            if (cDAO.modificar(cl)) {
                this.mensajeOk("Cliente actualizado existosamente");
                this.limpiar();
                this.listar();
                txtCorreo.setVisible(false);
                txtDireccion.setVisible(false);
                txtTelefono.setVisible(false);
                lblCorreo.setVisible(false);
                lblTelefono.setVisible(false);
                lblDireccion.setVisible(false);
                tabGeneral.setEnabledAt(0, true);
                tabGeneral.setEnabledAt(1, false);
                tabGeneral.setSelectedIndex(0);
            } else {
                this.mensajeError("Ocurrió un error, el cliente no fue actualizado");
            }

        } else {

            if (txtDireccion.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese una Direccion válida", "System", JOptionPane.WARNING_MESSAGE);
                txtDireccion.requestFocus();
                return;
            }
            if (txtCorreo.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un correo válido", "System", JOptionPane.WARNING_MESSAGE);
                txtCorreo.requestFocus();
                return;
            }
            if (txtTelefono.getText().length() > 9 || txtTelefono.getText().length() < 9) {
                JOptionPane.showMessageDialog(this, "El número de telefono no puede ser superior o inferior a 9 digitos", "System", JOptionPane.WARNING_MESSAGE);
                txtTelefono.requestFocus();
                return;
            }

            String rut = txtRut.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String correo = txtCorreo.getText();
            String direccion = txtDireccion.getText();
            String telefono = txtTelefono.getText();
            String fecha = txtFecha.getText();

            Correo cor = new Correo(correo);
            Direccion diec = new Direccion(direccion);
            Telefono tlf = new Telefono(telefono);

            cl = new Cliente(rut, nombre, apellido, fecha, tlf, diec, cor);

            if (cDAO.insertar(cl)) {
                this.mensajeOk("Cliente añadido existosamente");
                this.limpiar();
                this.listar();
                txtCorreo.setVisible(false);
                txtDireccion.setVisible(false);
                txtTelefono.setVisible(false);
                lblCorreo.setVisible(false);
                lblTelefono.setVisible(false);
                lblDireccion.setVisible(false);
                tabGeneral.setEnabledAt(0, true);
                tabGeneral.setEnabledAt(1, false);
                tabGeneral.setSelectedIndex(0);
            } else {
                this.mensajeError("Ocurrió error, el cliente no pude ser agregado");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTabbedPane tabGeneral;
    private javax.swing.JTable tablaListadoClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
