/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Correo;
import modelo.Trabajador;

/**
 *
 * @author Usuario
 */
public class FrmCorreos extends javax.swing.JInternalFrame {

    CorreoDAO cDAO = new CorreoDAO();
    TrabajadorDAO tDAO = new TrabajadorDAO();
    ClienteDAO clDAO = new ClienteDAO();
    String accion, person;

    /**
     * Creates new form FrmCorreos
     */
    public FrmCorreos() {
        initComponents();
        this.listar();
        this.cargarTrabajadores();
        this.cargarClientes();
        this.accion = "guardar";
        txtId.setVisible(false);
    }

    private void listar() {
        ArrayList<Object> listaTrabajadores = cDAO.getListTrabajadores();
        ArrayList<Object> listaClientes = cDAO.getListClientes();
        DefaultTableModel modeloTabla;

        String[] titulos = {"ID", "Nombre", "Apellido", "RUT", "Correo electronico", "Persona"};
        modeloTabla = new DefaultTableModel(null, titulos);

        for (Object obj : listaTrabajadores) {
            Trabajador trabajador = (Trabajador) obj;
            Object[] row = new Object[6];
            row[0] = trabajador.getCorreo().getIdCorreo();
            row[1] = trabajador.getNombre();
            row[2] = trabajador.getApellido();
            row[3] = trabajador.getRut();
            row[4] = trabajador.getCorreo().getCorreo();
            row[5] = "Trabajador";
            modeloTabla.addRow(row);
        }
        for (Object obj : listaClientes) {
            Cliente cliente = (Cliente) obj;
            Object[] row = new Object[6];
            row[0] = cliente.getCorreo().getIdCorreo();
            row[1] = cliente.getNombre();
            row[2] = cliente.getApellido();
            row[3] = cliente.getRut();
            row[4] = cliente.getCorreo().getCorreo();
            row[5] = "Cliente";
            modeloTabla.addRow(row);
        }

        tablaListadoCorreos.setModel(modeloTabla);
        tabGeneral.setEnabledAt(1, false);
    }

    private void limpiar() {
        txtCorreo.setText("");
        txtId.setText("");
        this.accion = "guardar";
    }

    private void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "System", JOptionPane.ERROR_MESSAGE);
    }

    private void mensajeOk(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "System", JOptionPane.INFORMATION_MESSAGE);
    }

    private void cargarTrabajadores() {
        DefaultComboBoxModel items = new DefaultComboBoxModel();
        ArrayList<Object> lista = tDAO.getList();

        for (Object obj : lista) {
            Trabajador trabajador = (Trabajador) obj;
            items.addElement(trabajador);
        }
        cboTrabajadores.setModel(items);
    }

    private void cargarClientes() {
        DefaultComboBoxModel items = new DefaultComboBoxModel();
        ArrayList<Object> lista = clDAO.getList();

        for (Object obj : lista) {
            Cliente cliente = (Cliente) obj;
            items.addElement(cliente);
        }
        cboClientes.setModel(items);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGeneral = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoCorreos = new javax.swing.JTable();
        btnNuevoCliente = new javax.swing.JButton();
        btnNuevoTrabajador = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        cboTrabajadores = new javax.swing.JComboBox<>();
        lblTrabajador = new javax.swing.JLabel();
        cboClientes = new javax.swing.JComboBox<>();
        lblClientes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Correos");

        tabGeneral.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaListadoCorreos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaListadoCorreos);

        btnNuevoCliente.setText("Nuevo correo clientes");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnNuevoTrabajador.setText("Nuevo correo trabajadores");
        btnNuevoTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTrabajadorActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoCliente)
                    .addComponent(btnNuevoTrabajador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCliente)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoTrabajador)
                    .addComponent(btnEditar))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        tabGeneral.addTab("Listado", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Correo(*)");

        lblTrabajador.setText("Trabajadores(*)");

        lblClientes.setText("Clientes(*)");

        jLabel4.setText("(*) Indica un campo obligatorio");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblClientes))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(lblTrabajador)
                        .addGap(42, 42, 42)
                        .addComponent(cboTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(btnGuardar)
                        .addGap(131, 131, 131)
                        .addComponent(btnVolver))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTrabajador))
                .addGap(27, 27, 27)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClientes))
                .addGap(77, 77, 77)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolver))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        tabGeneral.addTab("Mantenimiento", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        tabGeneral.setEnabledAt(1, true);
        tabGeneral.setEnabledAt(0, false);
        tabGeneral.setSelectedIndex(1);
        this.accion = "guardar";
        btnGuardar.setText("Guardar");
        lblTrabajador.setVisible(false);
        cboTrabajadores.setVisible(false);
        lblClientes.setVisible(true);
        cboClientes.setVisible(true);
        this.person = "Cliente";
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnNuevoTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTrabajadorActionPerformed
        tabGeneral.setEnabledAt(1, true);
        tabGeneral.setEnabledAt(0, false);
        tabGeneral.setSelectedIndex(1);
        this.accion = "guardar";
        btnGuardar.setText("Guardar");
        lblClientes.setVisible(false);
        cboClientes.setVisible(false);
        lblTrabajador.setVisible(true);
        cboTrabajadores.setVisible(true);
        this.person = "Trabajador";
    }//GEN-LAST:event_btnNuevoTrabajadorActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tablaListadoCorreos.getSelectedRowCount() == 1) {
            String persona = String.valueOf(tablaListadoCorreos.getValueAt(tablaListadoCorreos.getSelectedRow(), 5));
            if (persona.equals("Trabajador")) {

                String id = String.valueOf(tablaListadoCorreos.getValueAt(tablaListadoCorreos.getSelectedRow(), 0));
                String correo = String.valueOf(tablaListadoCorreos.getValueAt(tablaListadoCorreos.getSelectedRow(), 4));
                if (JOptionPane.showConfirmDialog(this, "Deseas eliminar la direccion de correo: " + correo + " ?", "Eliminar", JOptionPane.YES_NO_OPTION) == 0) {
                    if (cDAO.eliminar(Integer.parseInt(id))) {
                        this.mensajeOk("Registro eliminado");
                        this.listar();
                    } else {
                        this.mensajeError("Error, el regristro no pudo ser eliminado");
                    }
                }
            } else {
                String id = String.valueOf(tablaListadoCorreos.getValueAt(tablaListadoCorreos.getSelectedRow(), 0));
                String correo = String.valueOf(tablaListadoCorreos.getValueAt(tablaListadoCorreos.getSelectedRow(), 4));
                if (JOptionPane.showConfirmDialog(this, "Deseas eliminar la direccion de correo: " + correo + " ?", "Eliminar", JOptionPane.YES_NO_OPTION) == 0) {
                    if (cDAO.eliminarCl(Integer.parseInt(id))) {
                        this.mensajeOk("Registro eliminado");
                        this.listar();
                    } else {
                        this.mensajeError("Error, el regristro no pudo ser eliminado");
                    }

                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        tabGeneral.setEnabledAt(0, true);
        tabGeneral.setEnabledAt(1, false);
        tabGeneral.setSelectedIndex(0);
        cboTrabajadores.setVisible(false);
        lblTrabajador.setVisible(false);
        cboClientes.setVisible(false);
        lblClientes.setVisible(false);
        this.limpiar();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtCorreo.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un correo válido", "System", JOptionPane.WARNING_MESSAGE);
            txtCorreo.requestFocus();
            return;
        }

        if (this.accion.equals("editar")) {
            int id = Integer.parseInt(txtId.getText());
            String correo = txtCorreo.getText();
            Correo cr = new Correo(id, correo);
            if (cDAO.modificar(cr)) {
                this.mensajeOk("Direccion actualizada existosamente");
                this.limpiar();
                this.listar();
                tabGeneral.setEnabledAt(0, true);
                tabGeneral.setEnabledAt(1, false);
                tabGeneral.setSelectedIndex(0);
            } else {
                this.mensajeError("Ocurrió un error, el correo no fue actualizado");
            }

        } else {

            if (this.person.equals("Trabajador")) {
                String correo = txtCorreo.getText();
                Trabajador trabajador = (Trabajador) cboTrabajadores.getSelectedItem();
                Correo cr = new Correo(correo);
                int id = cDAO.insertarID(cr);
                if (id != 0) {
                    if (cDAO.insertarCorreoTrabajador(id, trabajador.getIdTrabajador())) {
                        this.mensajeOk("Direccion de correo añadida existosamente");
                        this.limpiar();
                        this.listar();
                        tabGeneral.setEnabledAt(0, true);
                        tabGeneral.setEnabledAt(1, false);
                        tabGeneral.setSelectedIndex(0);
                    } else {
                        this.mensajeError("Ocurrió un error al intentar agregar el correo");
                    }
                }
            } else {
                String correo = txtCorreo.getText();
                Cliente cliente = (Cliente) cboClientes.getSelectedItem();
                Correo cr = new Correo(correo);
                int id = cDAO.insertarID(cr);
                if (id != 0) {
                    if (cDAO.insertarCorreoCliente(id, cliente.getIdCliente())) {
                        this.mensajeOk("Direccion de correo añadida existosamente");
                        this.limpiar();
                        this.listar();
                        tabGeneral.setEnabledAt(0, true);
                        tabGeneral.setEnabledAt(1, false);
                        tabGeneral.setSelectedIndex(0);
                    } else {
                        this.mensajeError("Ocurrió un error al intentar agregar la direccion de correo");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tablaListadoCorreos.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoCorreos.getValueAt(tablaListadoCorreos.getSelectedRow(), 0));
            String correo = String.valueOf(tablaListadoCorreos.getValueAt(tablaListadoCorreos.getSelectedRow(), 4));

            txtId.setText(id);
            txtCorreo.setText(correo);

            tabGeneral.setEnabledAt(0, false);
            tabGeneral.setEnabledAt(1, true);
            tabGeneral.setSelectedIndex(1);
            this.accion = "editar";
            btnGuardar.setText("Editar");
            lblClientes.setVisible(false);
            cboClientes.setVisible(false);
            lblTrabajador.setVisible(false);
            cboTrabajadores.setVisible(false);

        } else {
            this.mensajeError("Seleccione 1 registro a editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoTrabajador;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboClientes;
    private javax.swing.JComboBox<String> cboTrabajadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblTrabajador;
    private javax.swing.JTabbedPane tabGeneral;
    private javax.swing.JTable tablaListadoCorreos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
