/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author Usuario
 */
public class FrmLibro extends javax.swing.JInternalFrame {

    LibroDAO lDAO = new LibroDAO();
    CategoriaDAO cDAO = new CategoriaDAO();
    AutorDAO aDAO = new AutorDAO();
    IdiomaDAO iDAO = new IdiomaDAO();
    EditorialDAO eDAO = new EditorialDAO();
    String accion;

    /**
     * Creates new form FrmLibro
     */
    public FrmLibro() {
        initComponents();
        this.listar();
        this.accion = "guardar";
        txtId.setVisible(false);
        this.cargarCategorias();
        this.cargarAutores();
        this.cargarEditorial();
        this.cargarIdiomas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void listar() {
        ArrayList<Object> lista = lDAO.getList();
        DefaultTableModel modeloTabla;

        String[] titulos = {"ID", "ISBN", "Titulo", "#Paginas", "Año de publicacion", "Precio", "Idioma", "Editorial", "Categoria", "Autor", "Estado"};
        modeloTabla = new DefaultTableModel(null, titulos);

        for (Object obj : lista) {
            Libro libro = (Libro) obj;
            Object[] row = new Object[11];
            row[0] = libro.getIdLibro();
            row[1] = libro.getIsbn();
            row[2] = libro.getTitulo();
            row[3] = libro.getCantidadPaginas();
            row[4] = libro.getFechaPublicacion();
            row[5] = libro.getPrecio();
            row[6] = libro.getIdioma().getIdioma();
            row[7] = libro.getEditorial().getNombreEditorial();
            row[8] = libro.getCategoria().getNombreCategoria();
            row[9] = libro.getAutor().getNombreAutor();
            switch (libro.getEstado()) {
                case 1:
                    row[10] = "Vendido";
                    break;
                case 2:
                    row[10] = "Arrendado";
                    break;
                case 3:
                    row[10] = "Disponible";
                    break;
                case 4:
                    row[10] = "No disponible";
                    break;
                default:
                    throw new AssertionError();
            }
            modeloTabla.addRow(row);
        }
        tablaListadoLibros.setModel(modeloTabla);
        tabGeneral.setEnabledAt(1, false);
    }

    private void limpiar() {
        txtTitulo.setText("");
        txtCantPag.setText("");
        txtFecha.setText("");
        txtId.setText("");
        txtIsbn.setText("");
        txtPrecio.setText("");
        this.accion = "guardar";
    }

    private void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "System", JOptionPane.ERROR_MESSAGE);
    }

    private void mensajeOk(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "System", JOptionPane.INFORMATION_MESSAGE);
    }

    private void cargarCategorias() {
        DefaultComboBoxModel items = new DefaultComboBoxModel();
        ArrayList<Object> lista = cDAO.getList();

        for (Object obj : lista) {
            Categoria categoria = (Categoria) obj;
            items.addElement(categoria);
        }
        cboCategorias.setModel(items);
    }

    private void cargarAutores() {
        DefaultComboBoxModel items = new DefaultComboBoxModel();
        ArrayList<Object> lista = aDAO.getList();

        for (Object obj : lista) {
            Autor autor = (Autor) obj;
            items.addElement(autor);
        }
        cboAutores.setModel(items);
    }

    private void cargarIdiomas() {
        DefaultComboBoxModel items = new DefaultComboBoxModel();
        ArrayList<Object> lista = iDAO.getList();

        for (Object obj : lista) {
            Idioma idioma = (Idioma) obj;
            items.addElement(idioma);
        }
        cboIdiomas.setModel(items);
    }

    private void cargarEditorial() {
        DefaultComboBoxModel items = new DefaultComboBoxModel();
        ArrayList<Object> lista = eDAO.getList();

        for (Object obj : lista) {
            Editorial editorial = (Editorial) obj;
            items.addElement(editorial);
        }
        cboEditoriales.setModel(items);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGeneral = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoLibros = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantPag = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cboCategorias = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboAutores = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboEditoriales = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboIdiomas = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Libros");

        tabGeneral.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaListadoLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaListadoLibros);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnActivar.setText("Activar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDesactivar.setText("Desactivar");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnActivar)
                .addGap(112, 112, 112)
                .addComponent(btnDesactivar)
                .addGap(103, 103, 103)
                .addComponent(btnEditar)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnActivar)
                    .addComponent(btnEditar)
                    .addComponent(btnDesactivar))
                .addGap(0, 71, Short.MAX_VALUE))
        );

        tabGeneral.addTab("Listado", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ISBN(*)");

        txtIsbn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel2.setText("Titulo(*)");

        jLabel3.setText("Cantidad de páginas(*)");

        txtCantPag.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCantPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantPagActionPerformed(evt);
            }
        });

        jLabel4.setText("Año de publicación");

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel5.setText("Precio(*)");

        txtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel6.setText("Categorias(*)");

        jLabel7.setText("Autor(*)");

        jLabel8.setText("Editorial(*)");

        jLabel9.setText("Idioma(*)");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel10.setText("(*) Indica campo obligatorio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(223, 223, 223))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(txtIsbn))
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFecha)
                                    .addComponent(txtCantPag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cboAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cboEditoriales, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cboIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel10)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cboAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(txtCantPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(cboEditoriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cboIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolver))
                .addGap(61, 61, 61))
        );

        tabGeneral.addTab("Mantenimiento", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabGeneral))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabGeneral)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantPagActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        tabGeneral.setEnabledAt(1, true);
        tabGeneral.setEnabledAt(0, false);
        tabGeneral.setSelectedIndex(1);
        this.accion = "guardar";
        btnGuardar.setText("Guardar");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tablaListadoLibros.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoLibros.getValueAt(tablaListadoLibros.getSelectedRow(), 0));
            Libro libro = lDAO.buscar(Integer.parseInt(id));

            txtId.setText(id);
            txtIsbn.setText(String.valueOf(libro.getIsbn()));
            txtCantPag.setText(String.valueOf(libro.getCantidadPaginas()));
            txtFecha.setText(libro.getFechaPublicacion());
            txtPrecio.setText(String.valueOf(libro.getPrecio()));
            txtTitulo.setText(libro.getTitulo());
            cboCategorias.setSelectedItem(new Categoria(libro.getCategoria().getIdCategoria(), libro.getCategoria().getNombreCategoria()));
            if (libro.getAutor().getApellidoPaterno() == null) {
                cboAutores.setSelectedItem(new Autor(libro.getAutor().getIdAutor(), libro.getAutor().getNombreAutor()));
            } else {
                cboAutores.setSelectedItem(new Autor(libro.getAutor().getIdAutor(), libro.getAutor().getNombreAutor(), libro.getAutor().getApellidoPaterno()));
            }
            cboEditoriales.setSelectedItem(new Editorial(libro.getEditorial().getIdEditorial(), libro.getEditorial().getNombreEditorial()));
            cboIdiomas.setSelectedItem(new Idioma(libro.getIdioma().getIdIdioma(), libro.getIdioma().getIdioma()));

            tabGeneral.setEnabledAt(0, false);
            tabGeneral.setEnabledAt(1, true);
            tabGeneral.setSelectedIndex(1);
            this.accion = "editar";
            btnGuardar.setText("Editar");

        } else {
            this.mensajeError("Seleccione 1 registro a editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        tabGeneral.setEnabledAt(0, true);
        tabGeneral.setEnabledAt(1, false);
        tabGeneral.setSelectedIndex(0);
        this.limpiar();

    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtTitulo.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un titulo válido", "System", JOptionPane.WARNING_MESSAGE);
            txtTitulo.requestFocus();
            return;
        }
        if (txtPrecio.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un precio", "System", JOptionPane.WARNING_MESSAGE);
            txtPrecio.requestFocus();
            return;
        }
        if (txtCantPag.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese una cantidad válida", "System", JOptionPane.WARNING_MESSAGE);
            txtCantPag.requestFocus();
            return;
        }
        if (txtIsbn.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ISBN valido", "System", JOptionPane.WARNING_MESSAGE);
            txtIsbn.requestFocus();
            return;
        }

        if (this.accion.equals("editar")) {
            int id = Integer.parseInt(txtId.getText());
            String Titulo = txtTitulo.getText();
            int isbn = Integer.parseInt(txtIsbn.getText());
            int pag = Integer.parseInt(txtCantPag.getText());
            String fecha = txtFecha.getText();
            int precio = Integer.parseInt(txtPrecio.getText());
            Categoria categoria = (Categoria) cboCategorias.getSelectedItem();
            Idioma idioma = (Idioma) cboIdiomas.getSelectedItem();
            Autor autor = (Autor) cboAutores.getSelectedItem();
            Editorial editorial = (Editorial) cboEditoriales.getSelectedItem();
            Libro libro = new Libro(id, isbn, Titulo, pag, fecha, precio, idioma, editorial, categoria, autor, 3);
            if (lDAO.modificar(libro)) {
                this.mensajeOk("Libro actualizado existosamente");
                this.limpiar();
                this.listar();
                tabGeneral.setEnabledAt(0, true);
                tabGeneral.setEnabledAt(1, false);
                tabGeneral.setSelectedIndex(0);
            } else {
                this.mensajeError("Ocurrió un error, el libro no fue actualizada");
            }

        } else {
            String Titulo = txtTitulo.getText();
            int isbn = Integer.parseInt(txtIsbn.getText());
            int pag = Integer.parseInt(txtCantPag.getText());
            String fecha = txtFecha.getText();
            int precio = Integer.parseInt(txtPrecio.getText());
            Categoria categoria = (Categoria) cboCategorias.getSelectedItem();
            Idioma idioma = (Idioma) cboIdiomas.getSelectedItem();
            Autor autor = (Autor) cboAutores.getSelectedItem();
            Editorial editorial = (Editorial) cboEditoriales.getSelectedItem();
            Libro libro = new Libro(isbn, Titulo, pag, fecha, precio, idioma, editorial, categoria, autor);
            if (lDAO.insertar(libro)) {
                this.mensajeOk("Categoria añadida existosamente");
                this.limpiar();
                this.listar();
                tabGeneral.setEnabledAt(0, true);
                tabGeneral.setEnabledAt(1, false);
                tabGeneral.setSelectedIndex(0);
            } else {
                this.mensajeError("El libro que intentas añadir, ya existe");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        if (tablaListadoLibros.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoLibros.getValueAt(tablaListadoLibros.getSelectedRow(), 0));
            String titulo = String.valueOf(tablaListadoLibros.getValueAt(tablaListadoLibros.getSelectedRow(), 2));
            String estado = String.valueOf(tablaListadoLibros.getValueAt(tablaListadoLibros.getSelectedRow(), 10));
            if (!estado.equals("Disponible")) {
                if (JOptionPane.showConfirmDialog(this, "Deseas activar el registro: " + titulo + " ?", "Activar", JOptionPane.YES_NO_OPTION) == 0) {

                    if (lDAO.activar(Integer.parseInt(id))) {
                        this.mensajeOk("Registro activado");
                        this.listar();
                    } else {
                        this.mensajeError("Error, el regristro no pudo ser activado");
                    }
                }
            } else {
                this.mensajeError("El libro ya está DISPONIBLE");
            }
        } else {
            this.mensajeError("Seleccione 1 registro a activar.");
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        if (tablaListadoLibros.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoLibros.getValueAt(tablaListadoLibros.getSelectedRow(), 0));
            String titulo = String.valueOf(tablaListadoLibros.getValueAt(tablaListadoLibros.getSelectedRow(), 2));
            String estado = String.valueOf(tablaListadoLibros.getValueAt(tablaListadoLibros.getSelectedRow(), 10));
            if (!estado.equals("No disponible")) {

                if (JOptionPane.showConfirmDialog(this, "Deseas desactiva el registro: " + titulo + " ?", "Desactivar", JOptionPane.YES_NO_OPTION) == 0) {

                    if (lDAO.eliminar(Integer.parseInt(id))) {
                        this.mensajeOk("Registro desactivado");
                        this.listar();
                    } else {
                        this.mensajeError("Error, el regristro no pudo ser desactivado");
                    }
                }
            } else {
                this.mensajeError("El libro ya tiene estado NO DISPONIBLE");
            }
        } else {
            this.mensajeError("Seleccione 1 registro a desactivar.");
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboAutores;
    private javax.swing.JComboBox<String> cboCategorias;
    private javax.swing.JComboBox<String> cboEditoriales;
    private javax.swing.JComboBox<String> cboIdiomas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabGeneral;
    private javax.swing.JTable tablaListadoLibros;
    private javax.swing.JFormattedTextField txtCantPag;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JFormattedTextField txtIsbn;
    private javax.swing.JFormattedTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
