/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author Usuario
 */
public class FrmTrabajadores extends javax.swing.JInternalFrame {

    private final TrabajadorDAO tDAO = new TrabajadorDAO();
    private String accion;

    /**
     * Creates new form FrmTrabajadores
     */
    public FrmTrabajadores() {
        initComponents();
        this.listar();
        this.accion = "guardar";
        txtId.setVisible(false);
        txtCorreo.setVisible(false);
        txtDireccion.setVisible(false);
        txtTelefono.setVisible(false);
        lblCorreo.setVisible(false);
        lblTelefono.setVisible(false);
        lblDireccion.setVisible(false);
    }

    private void listar() {
        ArrayList<Object> lista = tDAO.getList();
        DefaultTableModel modeloTabla;

        String[] titulos = {"ID", "RUT", "Nombre", "Apellido", "Fecha laboral", "Estado"};
        modeloTabla = new DefaultTableModel(null, titulos);

        for (Object obj : lista) {
            Trabajador trabajador = (Trabajador) obj;
            Object[] row = new Object[6];
            row[0] = trabajador.getIdTrabajador();
            row[1] = trabajador.getRut();
            row[2] = trabajador.getNombre();
            row[3] = trabajador.getApellido();
            row[4] = trabajador.getFechaLaboral();
            switch (trabajador.getEstado()) {
                case 1:
                    row[5] = "Activo";
                    break;
                case 2:
                    row[5] = "Inactivo";
                    break;
                default:
                    throw new AssertionError();
            }
            modeloTabla.addRow(row);
        }
        tablaListadoTrabajadores.setModel(modeloTabla);
        tabGeneral.setEnabledAt(1, false);
    }

    private void limpiar() {
        txtApellido.setText("");
        txtId.setText("");
        txtNombre.setText("");
        txtRut.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        this.accion = "guardar";
    }

    private void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "System", JOptionPane.ERROR_MESSAGE);
    }

    private void mensajeOk(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "System", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGeneral = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoTrabajadores = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Trabajadores");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaListadoTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaListadoTrabajadores);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnActivar.setText("Activar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        btnDesactivar.setText("Desactivar");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnNuevo)
                .addGap(101, 101, 101)
                .addComponent(btnActivar)
                .addGap(112, 112, 112)
                .addComponent(btnDesactivar)
                .addGap(96, 96, 96)
                .addComponent(btnEditar)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnActivar)
                    .addComponent(btnDesactivar)
                    .addComponent(btnEditar))
                .addGap(0, 64, Short.MAX_VALUE))
        );

        tabGeneral.addTab("Listado", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Rut(*)");

        jLabel2.setText("Nombre(*)");

        jLabel3.setText("Apellido(*)");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel4.setText("(*) Indica que es un ingreso obligatorio");

        lblTelefono.setText("Nro. Telefono(*)");

        lblDireccion.setText("Direccion(*)");

        lblCorreo.setText("Correo(*)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(185, 185, 185)
                        .addComponent(btnVolver)))
                .addGap(307, 307, 307))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblDireccion))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRut)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblCorreo))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(txtTelefono)))
                .addGap(53, 53, 53)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnGuardar))
                .addGap(40, 40, 40))
        );

        tabGeneral.addTab("Mantenimiento", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        tabGeneral.setEnabledAt(1, true);
        tabGeneral.setEnabledAt(0, false);
        tabGeneral.setSelectedIndex(1);
        this.accion = "guardar";
        btnGuardar.setText("Guardar");
        txtCorreo.setVisible(true);
        txtDireccion.setVisible(true);
        txtTelefono.setVisible(true);
        lblCorreo.setVisible(true);
        lblTelefono.setVisible(true);
        lblDireccion.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        tabGeneral.setEnabledAt(0, true);
        tabGeneral.setEnabledAt(1, false);
        tabGeneral.setSelectedIndex(0);
        txtCorreo.setVisible(false);
        txtDireccion.setVisible(false);
        txtTelefono.setVisible(false);
        lblCorreo.setVisible(false);
        lblTelefono.setVisible(false);
        lblDireccion.setVisible(false);
        this.limpiar();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        if (tablaListadoTrabajadores.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoTrabajadores.getValueAt(tablaListadoTrabajadores.getSelectedRow(), 0));
            String nombre = String.valueOf(tablaListadoTrabajadores.getValueAt(tablaListadoTrabajadores.getSelectedRow(), 2));
            String estado = String.valueOf(tablaListadoTrabajadores.getValueAt(tablaListadoTrabajadores.getSelectedRow(), 5));
            if (!estado.equals("Activo")) {
                if (JOptionPane.showConfirmDialog(this, "Deseas activar el trabajador: " + nombre + " ?", "Activar", JOptionPane.YES_NO_OPTION) == 0) {

                    if (tDAO.activar(Integer.parseInt(id))) {
                        this.mensajeOk("Registro activado");
                        this.listar();
                    } else {
                        this.mensajeError("Error, el regristro no pudo ser activado");
                    }
                }
            } else {
                this.mensajeError("El trabajador ya está ACTIVO");
            }
        } else {
            this.mensajeError("Seleccione 1 registro a activar.");
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        if (tablaListadoTrabajadores.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoTrabajadores.getValueAt(tablaListadoTrabajadores.getSelectedRow(), 0));
            String nombre = String.valueOf(tablaListadoTrabajadores.getValueAt(tablaListadoTrabajadores.getSelectedRow(), 2));
            String estado = String.valueOf(tablaListadoTrabajadores.getValueAt(tablaListadoTrabajadores.getSelectedRow(), 5));
            if (!estado.equals("Inactivo")) {
                if (JOptionPane.showConfirmDialog(this, "Deseas desactivar el trabajador: " + nombre + " ?", "Desactivar", JOptionPane.YES_NO_OPTION) == 0) {

                    if (tDAO.eliminar(Integer.parseInt(id))) {
                        this.mensajeOk("Registro desactivado");
                        this.listar();
                    } else {
                        this.mensajeError("Error, el regristro no pudo ser desactivado");
                    }
                }
            } else {
                this.mensajeError("El trabajador ya está DESACTIVADO");
            }
        } else {
            this.mensajeError("Seleccione 1 registro a activar.");
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tablaListadoTrabajadores.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListadoTrabajadores.getValueAt(tablaListadoTrabajadores.getSelectedRow(), 0));
            String rut = String.valueOf(tablaListadoTrabajadores.getValueAt(tablaListadoTrabajadores.getSelectedRow(), 1));
            String nombre = String.valueOf(tablaListadoTrabajadores.getValueAt(tablaListadoTrabajadores.getSelectedRow(), 2));
            String apellido = String.valueOf(tablaListadoTrabajadores.getValueAt(tablaListadoTrabajadores.getSelectedRow(), 3));

            txtId.setText(id);
            txtNombre.setText(nombre);
            txtRut.setText(rut);
            txtApellido.setText(apellido);

            tabGeneral.setEnabledAt(0, false);
            tabGeneral.setEnabledAt(1, true);
            tabGeneral.setSelectedIndex(1);
            this.accion = "editar";
            btnGuardar.setText("Editar");

        } else {
            this.mensajeError("Seleccione 1 registro a editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Trabajador tbj;
        if (txtNombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre válido", "System", JOptionPane.WARNING_MESSAGE);
            txtNombre.requestFocus();
            return;
        }
        if (txtApellido.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un apellido válido", "System", JOptionPane.WARNING_MESSAGE);
            txtApellido.requestFocus();
            return;
        }
        if (txtRut.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un rut válido", "System", JOptionPane.WARNING_MESSAGE);
            txtRut.requestFocus();
            return;
        }

        if (this.accion.equals("editar")) {
            int id = Integer.parseInt(txtId.getText());
            String rut = txtRut.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();

            tbj = new Trabajador(id, rut, nombre, apellido);

            if (tDAO.modificar(tbj)) {
                this.mensajeOk("Trabajador actualizado existosamente");
                this.limpiar();
                this.listar();
                txtCorreo.setVisible(false);
                txtDireccion.setVisible(false);
                txtTelefono.setVisible(false);
                lblCorreo.setVisible(false);
                lblTelefono.setVisible(false);
                lblDireccion.setVisible(false);
                tabGeneral.setEnabledAt(0, true);
                tabGeneral.setEnabledAt(1, false);
                tabGeneral.setSelectedIndex(0);
            } else {
                this.mensajeError("Ocurrió un error, el trabajador no fue actualizada");
            }

        } else {

            if (txtTelefono.getText().length() > 9 || txtTelefono.getText().length() < 9) {
                JOptionPane.showMessageDialog(this, "El número de telefono no puede ser superior o inferior a 9 digitos", "System", JOptionPane.WARNING_MESSAGE);
                txtTelefono.requestFocus();
                return;
            }
            if (txtDireccion.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese una Direccion válida", "System", JOptionPane.WARNING_MESSAGE);
                txtDireccion.requestFocus();
                return;
            }
            if (txtCorreo.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un correo válido", "System", JOptionPane.WARNING_MESSAGE);
                txtCorreo.requestFocus();
                return;
            }
            String rut = txtRut.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String correo = txtCorreo.getText();
            String direccion = txtDireccion.getText();
            String telefono = txtTelefono.getText();

            Correo cor = new Correo(correo);
            Direccion diec = new Direccion(direccion);
            Telefono tlf = new Telefono(telefono);

            tbj = new Trabajador(rut, nombre, apellido, tlf, diec, cor);

            if (tDAO.insertar(tbj)) {
                this.mensajeOk("Trabajador añadido existosamente");
                this.limpiar();
                this.listar();
                txtCorreo.setVisible(false);
                txtDireccion.setVisible(false);
                txtTelefono.setVisible(false);
                lblCorreo.setVisible(false);
                lblTelefono.setVisible(false);
                lblDireccion.setVisible(false);
                tabGeneral.setEnabledAt(0, true);
                tabGeneral.setEnabledAt(1, false);
                tabGeneral.setSelectedIndex(0);
            } else {
                this.mensajeError("El trabajador que intentas añadir, ya existe");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTabbedPane tabGeneral;
    private javax.swing.JTable tablaListadoTrabajadores;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
